sudo: required
language: java
services:
  - mysql
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

jdk:
    - oraclejdk8
install:
    cd desapp-groupB-backend/ && mvn install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8

script:
    mvn test -B

after_success:
  - mvn cobertura:cobertura
  - mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/cobertura/coverage.xml -DprojectToken=00afb194beed4589aaa835437d603e98 -DapiToken=123121
