  language:
      - java
  services:
      - mysql
  jdk:
      - oraclejdk8
      - openjdk8

  env:
      - TASKS='test'
  
  sudo:
      - false
  notifications:
      - email: 
          - dariofg93@gmail.com
