  language: java
  jdk: oraclejdk8
  services: mysql
      
  sudo: false
      
  notifications:
      - email: 
          - dariofg93@gmail.com


  mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  mvn test -B
